### ISSUE TITLE
Improvement in ReadMe.md file and contributing guidline.

### ISSUE THREAD

**Issue by Yash-Parsana** [Yash-Parsana/CrazyCoderApp#48]
Under this issue you have to descride what you will do.
Issue will be assigned to best one.

**Comment by shanvijha30** [comment]
@Yash-Parsana I would like to work on this issue.

**Comment by Anikinee** [comment]
> Under this issue you have to descride what you will do. Issue will be assigned to best one.

The changes I want to implement in the ReadMe.md file:
1. Introducing a section " TECHNOLOGY STACK" showing the badges of the different technologies and programming 
  languages used with a brief description of each.
2. Instead of displaying the repository status at the beginning a new section "REPO STATUS" can be introduced.
3. Adding README badges for the section "Supported Platforms".
4. Adding a "CONTRIBUTORS" section if there are any or a project admin section.
5. Adding various social media platform links to connect to the project admin.
6. Adding images of the website after the introduction section.

Regarding the Contributing Guideline section, along with the steps the command can also be provided for performing it.
For example: For cloning or making a branch, the associated command can be provided so that it becomes easy for the user to do so.

I would like to work on it. Please assign it to me @Yash-Parsana under GSSOC'23.

**Comment by peculiaruc** [comment]
@Yash-Parsana Assign this issue to me as you mentioned on Issue #45 for GSSoC'23

I will improve the ReadMe to include the following:

- The README file will be updated to meet Markdown Standard.
- Add the 'how to contribute to this project' section (The Contributing Guideline Section).
- Add Technologies used for this project with badges of each technology.
- Add Code of Conduct on the ReadMe
- Add the necessary badges and links to the Readme.
- Write guidelines on How to Make Your First Pull Request with associated commands and attach the necessary links
- Add App Screenshots/Images.

Please assign it to me under GSSoC'23.

**Comment by Yash-Parsana** [comment]
This issue is assigned to @Anikinee under GssoC'23.

**Comment by Anikinee** [comment]
> This issue is assigned to @Anikinee under GssoC'23.

Thank you for assigning!

**Comment by peculiaruc** [comment]
This is not just fair @Yash-Parsana
